### ISSUE TITLE
Generator Documentation missing piece

### ISSUE THREAD

**Issue by FrancescoLuzzi** [pro1code1hack/Your-Journey-To-Fluent-Python#52]
Hi!
I've noticed that you didn't cover a pretty neat property of generators, the send method!
I'll link you a nice [source](https://www.youtube.com/watch?v=tmeKsb2Fras) where you can learn about it!

Have fun!

**Comment by pro1code1hack** [comment]
Thaanks, will check it out shortly!

**Comment by dimpy1214** [comment]
Thank you!

**Comment by pro1code1hack** [comment]
Closing as this project has been refactored and now it's not a senior dev roamdap
